### ISSUE TITLE
Filtering multiple ds9 regions quickly with soxs.filter_events

### ISSUE THREAD

**Issue by Fred-Jennings** [lynx-x-ray-observatory/soxs#12]
Hi John, I hope you are well.

I have lots of pixels I'd like to mask in my event file. At the moment I do this;

```
for i, pixel_coords in enumerate(bad_pixels):
    reg = f"# Region file format: DS9\nimage\n-box(  {pixel_coords[0]}i, {pixel_coords[1]}i, 1i, 1i,0)\n" 
    soxs.filter_events(f"./my_evt.fits", f"./my_evt.fits", region=reg, emin = self.emin, emax = self.emax, overwrite=True)
```

but if I am running my program in parallel the amount of read/writing really slows things down. 

Is there a way to filter the event file with many ds9 regions at the same time? I have tried writing a ds9 file with each pixel on subsequent lines, then passing the filename to soxs.filter_events, and also tried modifying soxs' _region_filter function to always parse the string I give it as a region (not try it first as a filename; this sometimes throws an error as the path can end up being too long) like this

```
reg = f"# Region file format: DS9\nimage\n"
for i, pixel_coords in enumerate(bad_pixels):
    reg += f"-box(  {pixel_coords[0]}i, {pixel_coords[1]}i, 1i, 1i,0)\n" 
soxs.filter_events(f"./my_evt.fits", f"./my_evt.fits", region=reg, emin = self.emin, emax = self.emax, overwrite=True)
```

so that I can pass lots of pixels at once, but neither seem to work- both only seem to mask the first pixel in the file/string. Is there a way to pass an astropy composite region or similar?

Thanks,

Fred

**Comment by jzuhone** [comment]
Hi @FredJenningsAstro,

Whatever region AstroPy accepts, SOXS _ought_ to accept. Can you send me an example event file and composite region file for me to check?

John

**Comment by Fred-Jennings** [comment]
Hi John, many thanks for your reply.

I have sent a script and example events file to use (on slack, as it is above github's 25MB size limit). I use soxs version 3.3.0, and have shown several methods I've tried to do the multi-pixel masking efficiently. The biggest problem I have found is saving composite regions in astropy - I am not so familiar with astropy, but I don't know if it is even possible to save these compound regions- I get a "Cannot serialize a compound region" error.

Passing in a long ds9 string (ie having one box region per line) does not seem to work. Neither does writing this ds9 region string to a file then loading the file into SOXS. 

I have gotten things to work perfectly by modifying ```soxs.events._region_filter``` to allow the ```region``` argument to accept the region itself, rather than a region string or filename. Is it possible to just allow this in soxs?

Best,

Fred

**Comment by jzuhone** [comment]
@FredJenningsAstro if you have a solution, and if you don't mind, could you issue a PR for this? happy to receive one.

**Comment by Fred-Jennings** [comment]
Sure thing!

**Comment by Fred-Jennings** [comment]
Wow, my bad. filter_events already accepts just a bare astropy region. In the version of soxs I have been using there is an error thrown I think by a bug due to the line 409, in filter_events```elif not isinstance(Region):``` which needs 2 arguments, but in the latest update of soxs I have just checked and it appears fixed.  Apologies.
