### ISSUE TITLE
instrument_simulator path length issue

### ISSUE THREAD

**Issue by jakesbennett** [lynx-x-ray-observatory/soxs#17]
Hi!

If the length of the name of the path to a simput file given as input to instrument_simulator is longer than a certain number of characters (I brute force worked out 105 or longer...), then zero photons are found to come from the source. 

However if the file name is shorter, for the same file, photons are detected. 

No error is raised to say the file failed to be imported for example, you just get the "No events from any of the sources in the catalog were detected!” message. 

Shortening the filename "solves" this as a temporary workaround and I now get consistent results with the same file, for some long path lengths this could still be an issue though.

**Comment by jzuhone** [comment]
This is probably resolved by #19, feel free to reopen if not.
