### ISSUE TITLE
CHANTYPE issue 

### ISSUE THREAD

**Issue by CharlesERomero** [lynx-x-ray-observatory/soxs#33]
I just upgrade to SOXS 4.7.1 and am trying to run a simulation with lem_outer_array. When I try to run `soxs.instrument_simulator`, (adding backgrounds), I encounter an error regarding the CHANTYPE keyword in the rmf header.

SOXS downloaded the rms file and I can see CHANTYPE in the header (looking with 
If I manually try to access it with SOXS modules:
`instr = "lem_outer_array"
inst_spec = soxs.instrument_registry[instr]
rmf_file  = soxs.utils.get_data_file(inst_spec["rmf"])
rmf       = soxs.response.RedistributionMatrixFile(rmf_file)
print(rmf.header)`

the output is:

`XTENSION= 'BINTABLE'           / binary table extension                         
BITPIX  =                    8 / 8-bit bytes                                    
NAXIS   =                    2 / 2-dimensional binary table                     
NAXIS1  =                   22 / width of table in bytes                        
NAXIS2  =                12000 / number of rows in table                        
PCOUNT  =             10336512 / size of special data area                      
GCOUNT  =                    1 / one data group (required keyword)              
TFIELDS =                    6 / number of fields in each row                   
TTYPE1  = 'ENERG_LO'           / label for field   1                            
TFORM1  = 'E       '           / data format of field: 4-byte REAL              
TUNIT1  = 'keV     '           / physical unit of field                         
TTYPE2  = 'ENERG_HI'           / label for field   2                            
TFORM2  = 'E       '           / data format of field: 4-byte REAL              
TUNIT2  = 'keV     '           / physical unit of field                         
TTYPE3  = 'N_GRP   '           / label for field   3                            
TFORM3  = 'I       '           / data format of field: 2-byte INTEGER           
TTYPE4  = 'F_CHAN  '           / label for field   4                            
TFORM4  = '1I      '           / data format of field: 2-byte INTEGER           
TTYPE5  = 'N_CHAN  '           / label for field   5                            
TFORM5  = '1I      '           / data format of field: 2-byte INTEGER           
TTYPE6  = 'MATRIX  '           / label for field   6                            
TFORM6  = 'PE(217) '           / data format of field: variable length array    
EXTNAME = 'SPECRESP MATRIX'    / name of this binary table extension            
HDUCLASS= 'OGIP    '           / format conforms to OGIP standard               
HDUCLAS1= 'RESPONSE'           / dataset relates to spectral response           
HDUVERS1= '1.0.0   '           / Version of family of formats                   
HDUCLAS2= 'RSP_MATRIX'         / dataset is a spectral response matrix          
HDUVERS2= '1.1.0   '           / Version of format (OGIP memo CAL/GEN/92-002a)  
HDUCLAS3= 'FULL    '           / convolved w/ all effects (det + optics)        
TELESCOP= 'LEM     '           / mission/satellite name                         
INSTRUME= 'LEM     '           / instrument/detector name                       
FILTER  = '        '           / filter in use                                  
DETCHANS=                12000 / total number of detector channels              
LO_THRES=             0.000010 / lower threshold for stored matrix              
EFFAREA =             1.000000 / Area scaling factor                            
RMFVERSN= '1992a   '           / OGIP classification of FITS format             
HISTORY  FITS RMF extension written by WTRMF1 3.2.0                             
COMMENT Response with 2.5 eV Gaussian + 3% 12 eV low-energy exp. tail           
TLMIN4  =                    1 / starting value for F_CHAN                      
DATE    = '2023-09-13T01:45:44' / file creation date (YYYY-MM-DDThh:mm:ss UT)   `

It seems to be reading the SPECRESP MATRIX extension, which does not have the CHANTYPE keyword.

**Comment by jzuhone** [comment]
@CharlesERomero can you send the traceback of the actual error? this will help figure out where I need to look for a fix.

**Comment by jzuhone** [comment]
@CharlesERomero never mind, I can reproduce it now.

**Comment by CharlesERomero** [comment]
Got around to rerunning it with the updated SOXS, problem resolved! Thanks!
