### ISSUE TITLE
A typo on "Background Models in SOXS" page

### ISSUE THREAD

**Issue by liuguanfu1120** [lynx-x-ray-observatory/soxs#35]
I found a typo in the website [Background Models in SOXS](https://hea-www.cfa.harvard.edu/soxs/users_guide/background.html#):
In this website, it writes
"The `default` galactic foreground component is modeled as a sum of two thermal models with thermal broadening of emission lines, one absorbed, `bapec+tbabs*bapec`, with parameters:", 
note that it is `tbabs`. 
However, in the next line, it is 
"`wabs*bapec` Model 1, Hot Halo", which is `wabs` not `tbabs`.

**Comment by liuguanfu1120** [comment]
<img width="1353" alt="图片" src="https://github.com/lynx-x-ray-observatory/soxs/assets/94448438/941f38e1-1f6b-4da5-864f-65391b9cfa71">

**Comment by jzuhone** [comment]
Fixed in version 4.8.4, thanks for the report!
