### ISSUE TITLE
The galactic foreground model

### ISSUE THREAD

**Issue by tekkamanmaverick** [lynx-x-ray-observatory/soxs#4]
Hi John, 
Does the galactic foreground come from Hickox & Markevitch 2007? You referenced Hickox & Markevitch 2007, but I have searched and cannot find the fitting result you mentioned anywhere.
Where does the spectrum of foreground come from and how is this fitted?
Thank you!

**Comment by jzuhone** [comment]
This is a pretty standard model, but I admit I am not sure why we reference that paper. Will probably remove that line from the documentation.

**Comment by jzuhone** [comment]
Fixed in version 3.1.0
